title: Web/SPP/Settings Button
argTypes:
  iconType:
    defaultValue: settings
    options:
      Settings: settings
      FullScreen: full-screen
    control: radio
stories:
  - name: 1. Settings Button
    args:
      iconType: settings
      label: Settings
  - name: 2. Full Screen Button
    args:
      iconType: full-screen
      label: Full Screen
