$schema: https://git.drupalcode.org/project/drupal/-/raw/10.1.x/core/modules/sdc/src/metadata.schema.json
name: Settings button
description: A button that opens the preview in a new window.

libraryOverrides:
  dependencies:
    - core/drupal.dialog.ajax

props:
  type: object
  additionalProperties: false
  properties:
    iconType:
      type: string
      title: Icon Type
    label:
      type: string
      title: Text
